services:
  database:
    image: mariadb:lts
    env_file: .env
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wordpress-network
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - wordpress-network
    environment:
      PMA_HOST: ${DB_HOST}:${DB_PORT}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    depends_on:
      database:
        condition: service_healthy

  wordpress:
    image: wordpress:php8.4-fpm-alpine
    env_file: .env
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
      - ./src/wp-content:/var/www/html/wp-content
    networks:
      - wordpress-network
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}:${DB_PORT}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      database:
        condition: service_healthy

  webservice:
    image: nginx:stable-alpine-perl
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - wordpress:/var/www/html
      - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wordpress-network
    depends_on:
      - database
      - wordpress
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: curl --fail http://localhost:8080/ || exit 1
      start_period: 60s
      interval: 40s
      timeout: 30s
      retries: 3

volumes:
  db-data:
  wordpress:

networks:
  wordpress-network:
    driver: bridge
